services:
  solargraph:
    build: .
    command: bundle exec solargraph socket --host=0.0.0.0 --port=7658
    volumes:
      - ./:/usr/src/app:cached
      - gems:/usr/local/bundle
    ports:
      - "7658:7658"
