default: &defaults
  name: "HCB"

  push_api_key: <%= Credentials.fetch(:APPSIGNAL) %>

  ignore_errors:
    - ActionDispatch::Http::MimeNegotiation::InvalidType
    - ActionDispatch::Http::Parameters::ParseError
    - ActionController::BadRequest
    - ActionController::UnknownHttpMethod
    - ActionController::MethodNotAllowed
    - ActionController::UnknownFormat
    - ActionController::ParameterMissing
    - ActionController::InvalidCrossOriginRequest
    - ActionController::InvalidAuthenticityToken
    - ActiveRecord::RecordNotFound

production:
  <<: *defaults
  active: true
