# Rails custom configuration for application-wide constants
#
# WARNING: Application **secrets** do NOT belong here.
#          Please use Rails credentials for that purpose.
#
# Learn more: https://guides.rubyonrails.org/configuring.html#custom-configuration

shared:
  github_url: https://github.com/hackclub/hcb
  security_reporting_email: hcb-security@hackclub.com
