g_suite_mark_verifieds_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "GSuiteJob::MarkVerifieds"

g_suite_verify_all_job:
  cron: "0 */1 * * *" # run every 1 hour
  class: "GSuiteJob::VerifyAll"

g_suite_scan_verified_dns_job:
  cron: "0 12 * * *" # run every 1 day
  class: "GSuiteJob::ScanVerifiedDns"

pending_transaction_engine_nightly_job:
  cron: "0 */3 * * *" # run every 3 hour
  class: "PendingTransactionEngineJob::Nightly"

pending_event_mapping_engine_nightly_job:
  cron: "10,40 * * * *" # run every 30 minutes, but after pending_transaction_engine_nightly_job
  class: "PendingEventMappingEngineJob::Nightly"

transaction_engine_nightly_job:
  cron: "0 6 * * *" # run at 6am UTC each morning
  class: "TransactionEngineJob::Nightly"

transaction_grouping_engine_nightly_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "TransactionGroupingEngineJob::Nightly"

event_mapping_engine_nightly_job:
  cron: "0 7 * * *" # run at 7am UTC each morning
  class: "EventMappingEngineJob::Nightly"

sync_payouts_job:
  cron: "0,30 * * * *" # run every 30 minutes
  class: "SyncPayoutsJob"

fee_reimbursement_nightly_job:
  cron: "0 1 * * *" # run every 1 day
  class: "FeeReimbursementJob::Nightly"

bank_fee_weekly_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "BankFeeJob::Weekly"

disbursement_nightly_job:
  cron: "0 0 * * *" # run every 1 day.
  class: "DisbursementJob::Nightly"

disbursement_daily_job:
  cron: "0 13 * * *" # runs at 9am ET
  class: "DisbursementJob::Daily"
  queue: "default"

disbursement_hourly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "DisbursementJob::Hourly"

ach_transfer_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "AchTransferJob::Nightly"

ach_transfer_daily_job:
  cron: "0 13 * * *" # run daily at 9am ET
  class: "AchTransferJob::Daily"

invoice_opens_to_paids_job:
  cron: "30 * * * *" # run every hour
  class: "InvoiceJob::OpensToPaids"

donation_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "DonationJob::Nightly"

payout_nightly_job:
  cron: "0 0 * * *" # run every 1 day
  class: "PayoutJob::Nightly"

reimbursement_nightly_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "ReimbursementJob::Nightly"

bank_fee_nightly_job:
  cron: "*/30 2-23 * * *" # run every 30 minutes
  class: "BankFeeJob::Nightly"

fee_engine_hourly_job:
  cron: "0 */1 * * *" # run every 1 hours
  class: "FeeEngineJob::Hourly"

receipt_report_weekly_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "ReceiptReportJob::Weekly"

receipt_report_monthly_job:
  cron: "0 0 3 * *" # run first day of each month
  class: "ReceiptReportJob::Monthly"

column_reporting_monthly_job:
  cron: "0 0 1 * *" # run first day of each month
  class: "Column::ReportingJob"

column_statement_monthly_job:
  cron: "0 0 3 * *" # run third day of each month
  class: "Column::StatementJob"

stripe_card_nightly_job:
  cron: "0 7 * * *" # run every 1 day, after import
  class: "StripeCardJob::Nightly"

blazer_checks_nightly_job:
  cron: "0 8 * * *"
  class: "BlazerChecksJob"
  args: { schedule: "1 day" }

refresh_hcb_acronym_expansions_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "RefreshHcbAcronymExpansionsJob"

calculate_app_wide_metrics:
  cron: "0 */12 * * *" # run twice a day
  class: "MetricJobs::CalculateAppWide"

calculate_subjects_metrics:
  cron: "0 */12 * * *" # run twice a day
  class: "MetricJobs::CalculateSubjects"

ledger_audit_weekly_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "Admin::LedgerAudit::GenerateJob"

send_admin_reminders_job:
  cron: "0 7 * * *" # run at 7am UTC each morning
  class: "SendAdminRemindersJob"

gauge_online_user_count_job:
  cron: "*/5 * * * *" # Every 5 minutes
  class: "StatsdJob::GaugeOnlineUserCount"

user_subordinate_summary_job:
  cron: "0 12 * * mon" # noon UTC every Monday (7am eastern)
  class: "User::SubordinateSummaryJob"

headway_job:
  cron: "*/5 * * * *"
  class: "HeadwayJob"

user_sync_to_loops_job:
  cron: "0 7 * * *" # run every 1 day
  class: "User::SyncToLoopsJob"

update_teenager_column_job:
  cron: "0 7 * * *" # run every 1 day
  class: "User::UpdateTeenagerColumnJob"

card_grant_expiration_job:
  cron: "0 7 * * *" # run every 1 day
  class: "CardGrant::ExpirationJob"

card_grant_zero_job:
  cron: "0 7 * * *" # run every 1 day
  class: "CardGrant::ZeroJob"

stripe_service_fee_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "StripeServiceFeeJob"

user_seen_at_history_snapshot_job:
  cron: "0,30 * * * *" # twice every hour
  class: "User::SeenAtHistory::SnapshotJob"
